### PR TITLE
EULA Installation Fail + Ark Survival Evolved

### PR DESCRIPTION
**Pull request by DrPigi**
If the EULA is not accepted no files will be generated and the installation should fail.

### CODE REVIEW

**Comment by Scarsz** [comment]
I don't want the installation to fail if the EULA is not agreed upon. The user can choose to agree to it in `eula.txt`, it's just put as `false` in the case they don't agree.

**Comment by DrPigi** [comment]
If the EULA is not agreed files will not generate which will cause the installtion to fail. You won't be able to start the server later...

**Comment by Scarsz** [comment]
You can start the server later... All you have to do is open `eula.txt` and change `eula=false` to `eula=true` given you agree to follow the EULA

**Comment by DrPigi** [comment]
Ok

**Pull request closed without merging**
